require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SensesController do

  # This should return the minimal set of attributes required to create a valid
  # Sense. As you add validations to Sense, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SensesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all senses as @senses" do
      sense = Sense.create! valid_attributes
      get :index, {}, valid_session
      assigns(:senses).should eq([sense])
    end
  end

  describe "GET show" do
    it "assigns the requested sense as @sense" do
      sense = Sense.create! valid_attributes
      get :show, {:id => sense.to_param}, valid_session
      assigns(:sense).should eq(sense)
    end
  end

  describe "GET new" do
    it "assigns a new sense as @sense" do
      get :new, {}, valid_session
      assigns(:sense).should be_a_new(Sense)
    end
  end

  describe "GET edit" do
    it "assigns the requested sense as @sense" do
      sense = Sense.create! valid_attributes
      get :edit, {:id => sense.to_param}, valid_session
      assigns(:sense).should eq(sense)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Sense" do
        expect {
          post :create, {:sense => valid_attributes}, valid_session
        }.to change(Sense, :count).by(1)
      end

      it "assigns a newly created sense as @sense" do
        post :create, {:sense => valid_attributes}, valid_session
        assigns(:sense).should be_a(Sense)
        assigns(:sense).should be_persisted
      end

      it "redirects to the created sense" do
        post :create, {:sense => valid_attributes}, valid_session
        response.should redirect_to(Sense.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sense as @sense" do
        # Trigger the behavior that occurs when invalid params are submitted
        Sense.any_instance.stub(:save).and_return(false)
        post :create, {:sense => { "user_id" => "invalid value" }}, valid_session
        assigns(:sense).should be_a_new(Sense)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Sense.any_instance.stub(:save).and_return(false)
        post :create, {:sense => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sense" do
        sense = Sense.create! valid_attributes
        # Assuming there are no other senses in the database, this
        # specifies that the Sense created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Sense.any_instance.should_receive(:update).with({ "user_id" => "1" })
        put :update, {:id => sense.to_param, :sense => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested sense as @sense" do
        sense = Sense.create! valid_attributes
        put :update, {:id => sense.to_param, :sense => valid_attributes}, valid_session
        assigns(:sense).should eq(sense)
      end

      it "redirects to the sense" do
        sense = Sense.create! valid_attributes
        put :update, {:id => sense.to_param, :sense => valid_attributes}, valid_session
        response.should redirect_to(sense)
      end
    end

    describe "with invalid params" do
      it "assigns the sense as @sense" do
        sense = Sense.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Sense.any_instance.stub(:save).and_return(false)
        put :update, {:id => sense.to_param, :sense => { "user_id" => "invalid value" }}, valid_session
        assigns(:sense).should eq(sense)
      end

      it "re-renders the 'edit' template" do
        sense = Sense.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Sense.any_instance.stub(:save).and_return(false)
        put :update, {:id => sense.to_param, :sense => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sense" do
      sense = Sense.create! valid_attributes
      expect {
        delete :destroy, {:id => sense.to_param}, valid_session
      }.to change(Sense, :count).by(-1)
    end

    it "redirects to the senses list" do
      sense = Sense.create! valid_attributes
      delete :destroy, {:id => sense.to_param}, valid_session
      response.should redirect_to(senses_url)
    end
  end

end
